version: '3.7'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:prod

  dev:
    build: .
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev